# Generated by Django 5.0.7 on 2024-08-20 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_datetest'),
    ]

    operations = [
        migrations.AddField(
            model_name='datetest',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
