# Generated by Django 5.0.7 on 2024-08-20 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_datetest_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='datetest',
            name='both',
            field=models.DateTimeField(null=True),
        ),
    ]
