# Generated by Django 5.0.7 on 2024-08-20 14:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_datetest_both'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datetest',
            name='both',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
