# Generated by Django 5.0.7 on 2024-08-20 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_datetest_both'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
    ]
